name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cirrusci/android-sdk:34

    steps:
    - name: Repoyu Klonla
      uses: actions/checkout@v4

    - name: Gradle Wrapper Oluştur ve İzin Ver
      run: |
        gradle wrapper --gradle-version 8.6
        chmod +x gradlew

    - name: APK Derle
      run: ./gradlew assembleDebug --stacktrace

    - name: APK'yı Çıktı Olarak Yükle
      uses: actions/upload-artifact@v4
      with:
        name: SesliAsistan-Uygulamasi
        path: app/build/outputs/apk/debug/app-debug.apk
